'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property UltimaLista() As String
        Get
            Return CType(Me("UltimaLista"),String)
        End Get
        Set
            Me("UltimaLista") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property FormLeft() As Integer
        Get
            Return CType(Me("FormLeft"),Integer)
        End Get
        Set
            Me("FormLeft") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property FormTop() As Integer
        Get
            Return CType(Me("FormTop"),Integer)
        End Get
        Set
            Me("FormTop") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property Listas() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("Listas"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("Listas") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Repeat() As Boolean
        Get
            Return CType(Me("Repeat"),Boolean)
        End Get
        Set
            Me("Repeat") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Shuffle() As Boolean
        Get
            Return CType(Me("Shuffle"),Boolean)
        End Get
        Set
            Me("Shuffle") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MezclarCanciones() As Boolean
        Get
            Return CType(Me("MezclarCanciones"),Boolean)
        End Get
        Set
            Me("MezclarCanciones") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property CalcularTiempo() As Boolean
        Get
            Return CType(Me("CalcularTiempo"),Boolean)
        End Get
        Set
            Me("CalcularTiempo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
    Public Property MilisegundosMezcla() As Integer
        Get
            Return CType(Me("MilisegundosMezcla"),Integer)
        End Get
        Set
            Me("MilisegundosMezcla") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MinimizarTaskBar() As Boolean
        Get
            Return CType(Me("MinimizarTaskBar"),Boolean)
        End Get
        Set
            Me("MinimizarTaskBar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4000")>  _
    Public Property IntervaloRemoto() As Integer
        Get
            Return CType(Me("IntervaloRemoto"),Integer)
        End Get
        Set
            Me("IntervaloRemoto") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property silencioTotal() As Boolean
        Get
            Return CType(Me("silencioTotal"),Boolean)
        End Get
        Set
            Me("silencioTotal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expMenu() As Boolean
        Get
            Return CType(Me("expMenu"),Boolean)
        End Get
        Set
            Me("expMenu") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expActual() As Boolean
        Get
            Return CType(Me("expActual"),Boolean)
        End Get
        Set
            Me("expActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expListas() As Boolean
        Get
            Return CType(Me("expListas"),Boolean)
        End Get
        Set
            Me("expListas") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expListaActual() As Boolean
        Get
            Return CType(Me("expListaActual"),Boolean)
        End Get
        Set
            Me("expListaActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expOpcionesLista() As Boolean
        Get
            Return CType(Me("expOpcionesLista"),Boolean)
        End Get
        Set
            Me("expOpcionesLista") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property expBotonera() As Boolean
        Get
            Return CType(Me("expBotonera"),Boolean)
        End Get
        Set
            Me("expBotonera") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("00:00")>  _
    Public Property durActual() As String
        Get
            Return CType(Me("durActual"),String)
        End Get
        Set
            Me("durActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("670")>  _
    Public Property FormWidth() As Integer
        Get
            Return CType(Me("FormWidth"),Integer)
        End Get
        Set
            Me("FormWidth") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("550")>  _
    Public Property FormHeight() As Integer
        Get
            Return CType(Me("FormHeight"),Integer)
        End Get
        Set
            Me("FormHeight") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property campoClasificar() As Integer
        Get
            Return CType(Me("campoClasificar"),Integer)
        End Get
        Set
            Me("campoClasificar") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property InfoCompleta() As Boolean
        Get
            Return CType(Me("InfoCompleta"),Boolean)
        End Get
        Set
            Me("InfoCompleta") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property InfoUnaLinea() As Boolean
        Get
            Return CType(Me("InfoUnaLinea"),Boolean)
        End Get
        Set
            Me("InfoUnaLinea") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoVentana() As String
        Get
            Return CType(Me("fondoVentana"),String)
        End Get
        Set
            Me("fondoVentana") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoActual() As String
        Get
            Return CType(Me("fondoActual"),String)
        End Get
        Set
            Me("fondoActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoListas() As String
        Get
            Return CType(Me("fondoListas"),String)
        End Get
        Set
            Me("fondoListas") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoListaActual() As String
        Get
            Return CType(Me("fondoListaActual"),String)
        End Get
        Set
            Me("fondoListaActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoOpcionesListaActual() As String
        Get
            Return CType(Me("fondoOpcionesListaActual"),String)
        End Get
        Set
            Me("fondoOpcionesListaActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property fondoBotonera() As String
        Get
            Return CType(Me("fondoBotonera"),String)
        End Get
        Set
            Me("fondoBotonera") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property letraActual() As Global.System.Windows.Media.SolidColorBrush
        Get
            Return CType(Me("letraActual"),Global.System.Windows.Media.SolidColorBrush)
        End Get
        Set
            Me("letraActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property letraListas() As Global.System.Windows.Media.SolidColorBrush
        Get
            Return CType(Me("letraListas"),Global.System.Windows.Media.SolidColorBrush)
        End Get
        Set
            Me("letraListas") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property letraListaActual() As Global.System.Windows.Media.SolidColorBrush
        Get
            Return CType(Me("letraListaActual"),Global.System.Windows.Media.SolidColorBrush)
        End Get
        Set
            Me("letraListaActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property letraOpcionesListaActual() As Global.System.Windows.Media.SolidColorBrush
        Get
            Return CType(Me("letraOpcionesListaActual"),Global.System.Windows.Media.SolidColorBrush)
        End Get
        Set
            Me("letraOpcionesListaActual") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property letraBotonera() As Global.System.Windows.Media.SolidColorBrush
        Get
            Return CType(Me("letraBotonera"),Global.System.Windows.Media.SolidColorBrush)
        End Get
        Set
            Me("letraBotonera") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.gsPlayMusic.MySettings
            Get
                Return Global.gsPlayMusic.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
